# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy Next.js Static Site

on:
  push:
    branches: [ master ]

jobs:
  #Help From https://github.com/GabLeRoux/github-actions-examples/blob/e0468ce2731b08bd8b1f7cd09d0b94c541310693/.github/workflows/secret_based_conditions.yml
  checksecrets: 
    name: check if netlify secrets are defined
    runs-on: ubuntu-latest
    outputs:
      are_secrets_set: ${{ steps.checksecrets_job.outputs.are_secrets_set }}
    steps:
      - name: Decide whether to run the build and deploy action
        id: checksecrets_job
        env:
            NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_KEY }}
        run: |
            echo "auth token: ${{ env.NETLIFY_AUTH_TOKEN != ''}} site id: ${{env.NETLIFY_SITE_ID != ''}} "
            echo " NETLIFY_SITE_ID & NETLIFY_AUTH_TOKEN are set: ${{ env.NETLIFY_AUTH_TOKEN != '' && env.NETLIFY_SITE_ID != '' }}"
            echo "::set-output name=are_secrets_set::${{ env.NETLIFY_AUTH_TOKEN != '' && env.NETLIFY_SITE_ID != '' }}"

  build-and-deploy:
    needs: [checksecrets]
    if: needs.checksecrets.outputs.are_secrets_set == 'true'
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - run: npm install
    - run: npm run build 
    - run: npm run export
    - uses: netlify/actions/cli@master
      with:
          args: deploy --dir=out --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_KEY }}
